pipeline {
    agent any
    stages {
        stage('test') {
            steps {
                sh 'echo test'
            }
        }
        stage('failure') {
            steps {
                sh 'echo success'
            }
        }
    }
}
