pipeline {
  agent { label 'master' }
  stages {
    stage('test') {
      steps {
        script {
          def files = findFiles glob: '*'
          println files
        }
        sh 'echo test'
      }
    }
  }
}