pipeline {
  script {
    def nodes = nodesByLabel 'Group_A'
    println nodes
  }
  agent { label nodes[0] }
  stages {
    stage('test') {
      steps {
        
        sh 'echo test'
      }
    }
  }
}