@NonCPS
String[] findNodesByName(String pattern) {
  return jenkins.model.Jenkins.get().computers
    .findAll { it.node.selfLabel =~ pattern }
    .collect { it.node.selfLabel.name }
}

@NonCPS
String[] findNodesByLabel(String pattern) {
  return jenkins.model.Jenkins.get().computers
    .findAll { it.node.labelString =~ pattern }
    .collect { it.node.selfLabel.name }
}

println findNodesByName(/m/)
println findNodesByLabel(/Group_A/)